openapi: 3.0.0
info:
  title: API AWS Lamda - Dinamodb - Rds Myqsl
  description: API para crear cita de paciente
  version: 1.0.0
servers:
  - url: https://dl2h6oxr34.execute-api.us-east-2.amazonaws.com/dev
    description: Aws Endpoint
paths:
  /appointments:
    post:
      summary: Crear cita
      operationId: createAppointment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                insuredId:
                  type: string
                  example: "00001"
                scheduleId:
                  type: integer
                  example: 100
                countryISO:
                  type: string
                  enum: [PE, CL]
                  example: "PE"
                centerId:
                  type: integer
                  example: 1
                specialtyId:
                  type: integer
                  example: 2
                medicId:
                  type: integer
                  example: 3
                date:
                  type: string
                  format: date
                  example: "2023-10-01"
      responses:
        '200':
          description: Appointment created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  appointmentId:
                    type: string
                    example: "123e4567-e89b-12d3-a456-426614174000"
                  status:
                    type: string
                    example: "pending"
        '400':
          description: Invalid input
        '500':
          description: Internal server error

  /appointments/{insuredId}:
    get:
      summary: Lista cita por insuredId
      operationId: listByInsured
      parameters:
        - name: insuredId
          in: path
          required: true
          description: ID por insuredId
          schema:
            type: string
            example: "00001"
      responses:
        '200':
          description: lista de la cita
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    appointmentId:
                      type: string
                      example: "123e4567-e89b-12d3-a456-426614174000"
                    insuredId:
                      type: string
                      example: "00001"
                    scheduleId:
                      type: integer
                      example: 100
                    countryISO:
                      type: string
                      example: "PE"
                    status:
                      type: string
                      example: "pending"
                    createdAt:
                      type: string
                      format: date-time
                      example: "2023-10-01T12:00:00Z"
        '400':
          description: Id invalido
        '500':
          description: Error interno de servidor